"""first attempted migration

Revision ID: 058fa74c77c3
Revises: 
Create Date: 2023-07-05 12:53:01.012590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058fa74c77c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_vote_count', sa.Integer(), nullable=True),
    sa.Column('thread_university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_university_id'], ['universities.id'], name=op.f('fk_threads_thread_university_id_universities')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('user_post_count', sa.Integer(), nullable=True),
    sa.Column('user_university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_university_id'], ['universities.id'], name=op.f('fk_users_user_university_id_universities')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.String(), nullable=True),
    sa.Column('post_vote_count', sa.Integer(), nullable=True),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.Column('post_thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_thread_id'], ['threads.id'], name=op.f('fk_posts_post_thread_id_threads')),
    sa.ForeignKeyConstraint(['post_user_id'], ['users.id'], name=op.f('fk_posts_post_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('threads')
    op.drop_table('universities')
    # ### end Alembic commands ###
